# dual_layer_quantum_manager.md

The **DualLayerQuantumManager** owns both the `HybridGatedCollapseSimulator` and
`ChaoticCollapseOracle`. It monitors whether either simulator produces a valid
collapse and activates a deterministic `QuantumSimulator` fallback if needed.

- `initialize()` creates the simulators, starts the oracle and wires a
  `ChaoticSeedPromoter` so gated collapses may be overridden.
- `update()` checks the time since the last successful collapse. After 60 seconds
  without a valid seed it switches to fallback mode and logs a warning.
- `recordCollapse(valid)` updates internal statistics used by `update()`.
- `deterministicCollapse()` returns a seed generated by the fallback simulator.
- The constructor accepts an optional clock function for tests so time progression
  can be simulated without delays.

Location: `engine/modules/quantum/DualLayerQuantumManager.*`
